name = "SIsolver"
uuid = "6a5557e6-422c-4682-962b-fe159e569f73"
authors = ["Muhannad Alabdullateef <mh1995nd@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
